### PR TITLE
= instead of ==

### PR DESCRIPTION
**Pull request by jief666**

### CODE REVIEW

**Comment by tomkoen** [comment]
Absolutely, it's a bug: when compiling under debug, this would miss invalid data size!

**Comment by jief666** [comment]
You here ? :-)
See, I find some bug, I don't not always create them :-) :-)

**Comment by tomkoen** [comment]
> You here ? :-)

Sure, I'm a big fan of controlling code quality of open source which deals DMG...

**Comment by sgan81** [comment]
Thanks for finding that issue. I fixed it myself though.

**Comment by jief666** [comment]
Why not take pull request ? I think it's deserved credit to people who find bugs...

**Pull request closed without merging**
